---
title: "Untitled"
output: html_document
---

```{r, include=FALSE}
#Package Libraries
#install.packages("xaringan")
library(xaringan)
#install.packages("servr")
library(servr)
library(rio)
library(tidyverse)
library(ggplot2)
library(ggridges)
library(ggsci)
library(ggthemes)
library(car)
library(gridExtra)
#install.packages("ggpubr")
library(ggpubr)
#install.packages("showtext")
library(showtext)
#install.packages("prediction")
library(prediction)
font_add_google("Merriweather", "M", regular.wt = 400)
font_add_google("Josefin Sans", "JS", regular.wt = 400)
font_add_google("Work Sans", "WS", regular.wt = 400)
font_add_google("EB Garamond", "G", regular.wt = 400)
font_add_google("Raleway", "Rw", regular.wt = 400)
font_add_google("Averia Sans Libre", "Ave", regular.wt = 400)
font_add_google("Nova Round", "Nova", regular.wt = 400)
font_add_google("Carrois Gothic", "CG", regular.wt=400)
font_add_google("Jost", "Jost", regular.wt=400)
font_add_google("Oswald", "O", regular.wt=400)
font_add_google("Alfa Slab One", "ASO", regular.wt=400)
font_add_google("Passion One", "PO", regular.wt=400)
font_add_google("Roboto Condensed", "RC", regular.wt=400)
font_add_google("Yanone Kaffeesatz", "YF", regular.wt=600)
showtext_opts(dpi = 300)
showtext_auto(enable = TRUE)
#install.packages("devtools")
library(devtools)
#install_github("ryanburge/socsci")
library(socsci)
#install.packages("paletteer")
library(paletteer)
#install.packages("jtools")
library(jtools)
#install.packages("interactions")
library(interactions)
#install.packages("patchwork")
library(patchwork)
#install.packages("psych")
library(psych)
#install.packages("MASS")
library(MASS)
#install.packages("ragg")
library(ragg)
#install.packages("systemfonts")
library(systemfonts)
#install.packages("gtools")
library(gtools)
library(margins)
library(interactions)
#install.packages("harrypotter")
library(harrypotter)
#devtools::install_github("johannesbjork/LaCroixColoR")
library(LaCroixColoR)
library(wesanderson)
#devtools::install_github("edwinth/paletti")
library(paletti)


```


```{r, include=FALSE}
#Import Data, if you don't have access and want it, please email me at dennen_j1@denison.edu
library(readr)
m21 <- read_csv("March_2021_deidentified_565.csv")

#Make all variables lowercase
m21 <- m21 %>% rename_all(tolower) 
rm(March_2021_deidentified_565)

library(scales)
show_col(pal_futurama("planetexpress")(12))

```

```{r demos, include=FALSE}
#Demographic stuff
#Basic renaming
m21 <- m21 %>% mutate(sexo=q55,
                      faminc=q58,
                      ed=q59,
                      year=q62,
                      pid8=q3,
                      polint=6-q2)

#Gender stuff
m21 <- m21 %>% mutate(q54_1=car::recode(q54_1, "NA=0"),
                      q54_2=car::recode(q54_2, "NA=0"),
                      q54_3=car::recode(q54_3, "NA=0"),
                      q54_4=car::recode(q54_4, "NA=0"))

m21 <- m21 %>% mutate(gender4= frcode(q54_1==1 ~ "Male",
                                      q54_2==1 ~ "Female",
                                      q54_3==1 ~ "Transgender",
                                      q54_4==1 ~ "Non-binary"))

#Sexual orientation
m21 <- m21 %>% mutate(sexo=frcode(q55==1 ~ "Heterosexual",
                                  q55==2 ~ "Homosexual",
                                  q55==3 ~ "Bisexual",
                                  q55==4 ~ "Pansexual",
                                  q55==5 ~ "Asexual",
                                  q55==6 ~ "Other"))

#Graduation year
m21 <- m21 %>% mutate(yearf=frcode(year==1 ~ "2021",
                                   year==2 ~ "2022",
                                   year==3 ~ "2023",
                                   year==4 ~ "2024"))

#Race
m21 <- m21 %>% mutate(white=car::recode(q57_1, "NA=0"),
                      hispanic=car::recode(q57_2, "NA=0"),
                      black=car::recode(q57_3, "NA=0"),
                      asian=car::recode(q57_4, "NA=0"),
                      other=car::recode(q57_5, "NA=0"))

#A single race variable (e.g., white only)
m21 <- m21 %>% mutate(race=case_when(black==1 ~ "Black",
                                     asian==1 & (black!=1 & hispanic!=1) ~ "Asian",
                                     hispanic==1 ~ "Hispanic",
                                     other==1 & (black!=1 & hispanic!=1 & asian!=1)~ "Other",
                                     white==1 & (black!=1 & hispanic!=1 & asian!=1 & other!=1) ~ "White"))
m21 %>% ct(race)


```

```{r Politics stuff (ideo, pid8, polint), include=FALSE}
#Ideology stuff
#Changing NAs to zeroes
m21 <- m21 %>% mutate(q61_1=car::recode(q61_1, "NA=0"),
                      q61_2=car::recode(q61_2, "NA=0"),
                      q61_3=car::recode(q61_3, "NA=0"),
                      q61_4=car::recode(q61_4, "NA=0"),
                      q61_5=car::recode(q61_5, "NA=0"),
                      q61_6=car::recode(q61_6, "NA=0"),
                      q61_7=car::recode(q61_7, "NA=0"))
#Proglib
m21 <- m21 %>% mutate(proglib=frcode(q61_1==1 & q61_2==0 ~ "Progressive\nOnly",
                                     q61_1==0 & q61_2==1 ~ "Liberal\nOnly",
                                     q61_1==1 & q61_2==1 ~ "Both Prog\n& Lib",
                                     q61_4==1|q61_5==1|q61_3==1|q61_6==1|q61_7==1 ~ "Other"))


#Making all ideologies (with proglib)
m21 <- m21 %>% mutate(ideo=frcode(q61_1==1 & q61_2==0 ~ "Progressive\nOnly",
                                  q61_1==0 & q61_2==1 ~ "Liberal\nOnly",
                                  q61_1==1 & q61_2==1 ~ "Both Prog\n& Lib",
                                  q61_4==1 ~ "Conservative",
                                  q61_5==1 ~ "Alt-right",
                                  q61_3==1 ~ "Moderate",
                                  q61_6==1 ~ "Libertarian",
                                  q61_7==1 ~ "Other"))
#Total number of people choosing one of the ideologies
m21 <- m21 %>% mutate(ideotot=frcode(q61_1==1 ~ "Progressive",
                                     q61_2==1 ~ "Liberal",
                                     q61_4==1 ~ "Conservative",
                                     q61_5==1 ~ "Alt-right",
                                     q61_3==1 ~ "Moderate",
                                     q61_6==1 ~ "Libertarian",
                                     q61_7==1 ~ "Other"))

#Political party
m21 <- m21 %>% mutate(pid8f=frcode(pid8==1 ~ "Strong\nDemocrat",
                                   pid8==2 ~ "Democrat",
                                   pid8==3 ~ "Lean\nDemocrat",
                                   pid8==4 ~ "Independent",
                                   pid8==5 ~ "Lean\nRepublican",
                                   pid8==6 ~ "Republican",
                                   pid8==7 ~ "Strong\nRepublican",
                                   pid8==8 ~ "Other"))

#Simplifying party into 4 categories
m21 <- m21 %>% mutate(pid4f=frcode(pid8==1 | pid8==2 | pid8==3 ~ "Democrat",
                                   pid8==4 ~ "Independent",
                                   pid8==5 | pid8==6 | pid8==7 ~ "Republican",
                                   pid8==8 ~ "Other"))

#Partisan strength
m21 <- m21 %>% mutate(pidst=car::recode(pid8, "1=4; 2=3; 3=2; 4=1; 5=2; 6=3; 7=4; 8=1"))
m21 <- m21 %>% mutate(pidstf=frcode(pid8==1 | pid8==7 ~ "Strong\nPartisan",
                                    pid8==2 | pid8==6 ~ "Partisan",
                                    pid8==3 | pid8==5 ~ "Lean Partisan",
                                    pid8==4 ~ "Independent",
                                    pid8==8 ~ "Other"))


#Political interest
m21 <- m21 %>% mutate(polintf=frcode(polint==1 ~ "Not at all\ninterested",
                                     polint==2 ~ "Not very\ninterested",
                                     polint==3 ~ "Somewhat\ninterested",
                                     polint==4 ~ "Very\ninterested",
                                     polint==5 ~ "Extremely\ninterested"))

```

```{r QAnon}
#QAnon variable
m21 <- m21 %>% mutate(q6r=6-q6)
m21 <- m21 %>% mutate(q6rf=frcode(q6r==1 ~ "Strongly\nDisagree",
                                  q6r==2 ~ "Somewhat\nDisagree",
                                  q6r==3 ~ "Neither Agree\nNor Disagree",
                                  q6r==4 ~ "Somewhat\nAgree",
                                  q6r==5 ~ "Strongly\nAgree"))
#Making it a 0-1 variable
m21 <- m21 %>% mutate(q6rc=car::recode(q6r, "1:3=0; 4:5=1")) 
m21 <- m21 %>% mutate(q6lab=frcode(q6rc==0 ~ "Disagree/No Opinion",
                                   q6rc==1 ~ "Agree"))
#Three point variable
m21 <- m21 %>% mutate(q6lab3=frcode(q6r==1|q6r==2 ~ "Disagree",
                                    q6r==3 ~ "Neither Agree\nnor Disagree",
                                    q6r==4|q6r==5 ~ "Agree"))

#Proud/Embarrassed of US Democracy
m21 <- m21 %>% mutate(q39_1f=frcode(q39_1== 1 ~ "Very Embarrassed", 
                                    q39_1== 2 ~ "Somewhat Embarrassed", 
                                    q39_1== 3 ~ "Neither Embarrassed\nnor Proud",
                                    q39_1== 4 ~ "Somewhat Proud",
                                    q39_1== 5 ~ "Very Proud"))
```

```{r Involvement and stress}
#Number of types of activities involved in
m21 <- m21 %>% rowwise() %>% mutate(invtot=sum(q43_1, 
                                               q43_2, 
                                               q43_3,
                                               q43_4, 
                                               q43_5, 
                                               q43_6, 
                                               q43_7, 
                                               q43_8,
                                               q43_9,
                                               q43_10,
                                               q43_11, na.rm=TRUE)) %>% ungroup()
m21 <- m21 %>% mutate(invtotf=as.factor(invtot))


#Factoring the variables for activities during the day
m21 <- m21 %>% mutate(study=as.factor(q16_3),
                      sleep=as.factor(q16_5),
                      eat=as.factor(q16_1),
                      attend=as.factor(q16_2),
                      exercise=as.factor(q16_4),
                      meet=as.factor(q16_6),
                      hang=as.factor(q16_7),
                      tv=as.factor(q16_8),
                      sm=as.factor(q16_9))


#Grouping Stress Levels
m21 <- m21 %>% mutate(cucumber4 = frcode(q20_1>= 1 & q20_1 <= 25 ~ 'Cool as a Cucumber',
                                         q20_1>= 26 & q20_1 <= 50 ~ 'Less Cool',
                                         q20_1>= 51 & q20_1 <= 75 ~ 'More Stressed',
                                         q20_1>= 76 & q20_1 <= 100 ~ 'Extremely Stressed'))



```

```{r Gathering different variables}
m21_major <- m21 %>% gather(key="t_major", value="p_major", 
                                q63_1, q63_2, q63_3, q63_4, q63_5, q63_6, na.rm=TRUE) %>% 
  mutate(t_major=frcode(t_major=="q63_1" ~ "Social Sciences",
                        t_major=="q63_2" ~ "Sciences",
                        t_major=="q63_3" ~ "Humanities",
                        t_major=="q63_4" ~ "Arts",
                        t_major=="q63_5" ~ "Interdisciplinary \nPrograms",
                        t_major=="q63_6" ~ "Undecided")) 

#Campus involvement
m21 <- m21 %>% mutate(q43_1=car::recode(q43_1, "NA=0"),
                      q43_2=car::recode(q43_2, "NA=0"),
                      q43_3=car::recode(q43_3, "NA=0"),
                      q43_4=car::recode(q43_4, "NA=0"),
                      q43_5=car::recode(q43_5, "NA=0"),
                      q43_6=car::recode(q43_6, "NA=0"),
                      q43_7=car::recode(q43_7, "NA=0"),
                      q43_8=car::recode(q43_8, "NA=0"),
                      q43_9=car::recode(q43_9, "NA=0"),
                      q43_10=car::recode(q43_10, "NA=0"),
                      q43_11=car::recode(q43_11, "NA=0"))

m21_inv <- m21 %>% gather(key="t_inv", value="p_inv", 
                                q43_1, q43_2, q43_3, q43_4, q43_5, q43_6,
                                q43_7, q43_8, q43_9, q43_10, q43_11,  na.rm=TRUE) %>% 
  mutate(t_inv=frcode(t_inv=="q43_1" ~ "Varsity Sports",
                      t_inv=="q43_2" ~ "Club Sports",
                      t_inv=="q43_3" ~ "DCGA",
                      t_inv=="q43_4" ~ "Employment",
                      t_inv=="q43_5" ~ "Performing/Art Groups",
                      t_inv=="q43_6" ~ "Greek Life",
                      t_inv=="q43_7" ~ "Community Service",
                      t_inv=="q43_8" ~ "Social Justice/ Advocacy",
                      t_inv=="q43_9" ~ "Religious/Spiritual Life",
                      t_inv=="q43_10" ~ "Cross Cultural Engagement",
                      t_inv=="q43_11" ~ "Other"))

m21_str <- m21 %>% gather(key="t_str", value="p_str", 
                                q21_1, q21_2, q21_3, q21_4, q21_5, q21_6,
                                q21_7, q21_8, q21_9,   na.rm=TRUE) %>% 
  mutate(t_str=frcode(t_str=="q21_1" ~ "Academics",
                      t_str=="q21_2" ~ "Personal Finances",
                      t_str=="q21_3" ~ "Family",
                      t_str=="q21_4" ~ "Mental Health",
                      t_str=="q21_5" ~ "Relationships with Friends",
                      t_str=="q21_6" ~ "Covid-19",
                      t_str=="q21_7" ~ "Roommates",
                      t_str=="q21_8" ~ "Food: Figuring Out\nWhat to Eat Next",
                      t_str=="q21_9" ~ "Food: Figuring How\nMuch to Eat Next"))

m21_day <- m21 %>% filter(q16_1<6) %>% gather(key="t_day", value="p_day", 
                                q16_1, q16_2, q16_3, q16_4, q16_5, q16_6,
                                q16_7, q16_8, q16_9,   na.rm=TRUE) %>% 
  mutate(t_day=frcode(t_day=="q16_1" ~ "Eating",
                      t_day=="q16_2" ~ "Attending Classes",
                      t_day=="q16_3" ~ "Studying/Homework",
                      t_day=="q16_4" ~ "Exercising",
                      t_day=="q16_5" ~ "Sleeping",
                      t_day=="q16_6" ~ "Meetings",
                      t_day=="q16_7" ~ "Hanging Out With Friends",
                      t_day=="q16_8" ~ "Watching TV + Video Games",
                      t_day=="q16_9" ~ "Social Media"))

m21_day1 <- m21 %>% gather(key="t_day", value="p_day", 
                                q16_4, q16_5,q16_9, na.rm=TRUE) %>% 
  mutate(t_day=frcode(t_day=="q16_4" ~ "Exercising",
                      t_day=="q16_5" ~ "Sleeping",
                      t_day=="q16_9" ~ "Social Media"))

m21_day1 <- m21_day1 %>% mutate(p_dayf=as.factor(p_day))
m21<- m21 %>% mutate(drink=as.factor(q23))


```

```{r making color palette}
gbh <- c("#ABDDDE", "#FD6467", "#5B1A18", "#D67236","#E6A0C4", "#C6CDF7", "#D8A499", "#7294D4", "#46ACC8")
viz_palette(gbh)
gbh_fill  <- get_scale_fill(get_pal(gbh))
gbh_color <- get_scale_color(get_pal(gbh))

dj <- c( "#00A08A", "#F2AD00", "#F98400", "#5BBCD6", "#ECCBAE", "#046C9A", "#D69C4E", "#ABDDDE", "#000000")
viz_palette(dj)
dj_fill  <- get_scale_fill(get_pal(dj))
dj_color <- get_scale_color(get_pal(dj))

```

```{r}
m21_str %>% 
  group_by(t_str) %>% 
  mean_ci(p_str, ci=.76) %>% 
  ggplot(., aes(x=reorder(t_str,mean), y=mean, fill= t_str)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  coord_flip() +
  theme_hc() +
  theme(text=element_text(family="Jost", size=12),
        legend.position = "blank",
        title = element_text(size=16)
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="Jost", nudge_y = -1) +
  labs(y="Number of Hours Doing Homework", x=NULL, 
       title="Even in the Middle of a Pandemic,\nAcademics Are by Far the Most Stressful Aspect of Students' Lives",
       caption="Source: March 2021 Survey.\nNote: Confidence Intervals Are Equivalent to a 90% Test of Statistical Significance When Two Are Compared") +
  gbh_fill()

```


```{r Causes for Academic stress}
#Study and stress levels
m21 %>% 
  group_by(study) %>% filter(q16_3!="NA") %>% 
  mean_ci(q21_1, ci=.76) %>% 
  ggplot(., aes(x=study , y=mean, fill= study)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  theme_hc() +
  theme(text=element_text(family="O", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="O", nudge_y = -1) +
  labs(y="Number of Hours Doing Homework", x=NULL, 
       title="More Homework is Related to More Academic Stress",
       caption="Source: March 2021 Survey.\nNote: Confidence Intervals Are Equivalent to a 90% Test of Statistical Significance When Two Are Compared") +
  scale_fill_futurama()

#Sleep and stress levels
m21 %>% 
  group_by(sleep) %>% filter(q16_5!="NA") %>% filter(q16_5>4) %>%  
  mean_ci(q21_1, ci=.76) %>% 
  ggplot(., aes(x=sleep , y=mean, fill= sleep)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  theme_hc() +
  theme(text=element_text(family="O", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="O", nudge_y = -1) +
  scale_y_continuous(limits = c(0,10), 
                     labels = c("Not At All\nStressful", "2.5", "5", "7.5", "Very\nStressful")) +
  labs(x="Number of Hours Doing Sleeping", y=NULL, 
       title="Seven Hours of Sleep Is The Perfect Amount To Reduce Academic Stress",
       caption="Source: March 2021 Survey.\nNote: Confidence Intervals Are Equivalent to a 90% Test of Statistical Significance When Two Are Compared") +
  scale_fill_futurama()

#Eating and stress levels
m21 %>% 
  group_by(eat) %>% filter(q16_1!="NA") %>% filter(q16_1<6) %>%  
  mean_ci(q21_1, ci=.76) %>% 
  ggplot(., aes(x=eat , y=mean, fill= eat)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  theme_hc() +
  theme(text=element_text(family="O", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="O", nudge_y = -1) +
  scale_y_continuous(limits = c(0,10), 
                     labels = c("Not At All\nStressful", "2.5", "5", "7.5", "Very\nStressful")) +
  labs(x="Number of Hours Eating", y=NULL, 
       title="Eating",
       caption="Source: March 2021 Survey.\nNote: Confidence Intervals Are Equivalent to a 90% Test of Statistical Significance When Two Are Compared") +
  scale_fill_futurama()

#Attending class
m21 %>% 
  group_by(attend) %>% filter(q16_2!="NA") %>% filter(q16_2<7) %>%
  mean_ci(q21_1, ci=.76) %>% 
  ggplot(., aes(x=attend , y=mean, fill= attend)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  theme_hc() +
  theme(text=element_text(family="O", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="O", nudge_y = -1) +
  scale_y_continuous(limits = c(0,10), 
                     labels = c("Not At All\nStressful", "2.5", "5", "7.5", "Very\nStressful")) +
  labs(x="Number of Hours Going to Class", y=NULL, 
       title="Attending classes",
       caption="Source: March 2021 Survey.\nNote: Confidence Intervals Are Equivalent to a 90% Test of Statistical Significance When Two Are Compared") +
  scale_fill_futurama()

#Exercise
m21 %>% 
  group_by(exercise) %>% filter(q16_4!="NA") %>% filter(q16_4<5) %>%
  mean_ci(q21_1, ci=.76) %>% 
  ggplot(., aes(x=exercise , y=mean, fill= exercise)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  theme_hc() +
  theme(text=element_text(family="O", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="O", nudge_y = -1) +
  scale_y_continuous(limits = c(0,10), 
                     labels = c("Not At All\nStressful", "2.5", "5", "7.5", "Very\nStressful")) +
  labs(x="Number of Hours Doing Exercise", y=NULL, 
       title="One to Two Hours of Exercise Helps Alleviate Academic Stress",
       caption="Source: March 2021 Survey.\nNote: Confidence Intervals Are Equivalent to a 90% Test of Statistical Significance When Two Are Compared") +
  scale_fill_futurama()

#Meetings
m21 %>% 
  group_by(meet) %>% filter(q16_6!="NA") %>% filter(q16_6<4) %>%
  mean_ci(q21_1, ci=.76) %>% 
  ggplot(., aes(x=meet , y=mean, fill= meet)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  theme_hc() +
  theme(text=element_text(family="O", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="O", nudge_y = -1) +
  scale_y_continuous(limits = c(0,10), 
                     labels = c("Not At All\nStressful", "2.5", "5", "7.5", "Very\nStressful")) +
  labs(x="Number of Hours Going to Meetings", y=NULL, 
       title="Meetings",
       caption="Source: March 2021 Survey.\nNote: Confidence Intervals Are Equivalent to a 90% Test of Statistical Significance When Two Are Compared") +
  scale_fill_futurama()

#Hanging out with Friends
m21 %>% 
  group_by(hang) %>% filter(hang!="NA") %>%  
  mean_ci(q21_1, ci=.76) %>% 
  ggplot(., aes(x=hang , y=mean, fill= hang)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  theme_hc() +
  theme(text=element_text(family="O", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="O", nudge_y = -1) +
  scale_y_continuous(limits = c(0,10), 
                     labels = c("Not At All\nStressful", "2.5", "5", "7.5", "Very\nStressful")) +
  labs(x="Number of Hours With Friends", y=NULL, 
       title="Hanging out with Friends",
       caption="Source: March 2021 Survey.\nNote: Confidence Intervals Are Equivalent to a 90% Test of Statistical Significance When Two Are Compared") +
  scale_fill_futurama()

#Watching TV/Video Games
m21 %>% 
  group_by(tv) %>% filter(tv!="NA") %>%  filter(q16_8<6) %>%
  mean_ci(q21_1, ci=.76) %>% 
  ggplot(., aes(x=tv , y=mean, fill= tv)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  theme_hc() +
  theme(text=element_text(family="O", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="O", nudge_y = -1) +
  scale_y_continuous(limits = c(0,10), 
                     labels = c("Not At All\nStressful", "2.5", "5", "7.5", "Very\nStressful")) +
  labs(x="Number of Hours Watching TV", y=NULL, 
       title="Watching TV/Video Games",
       caption="Source: March 2021 Survey.\nNote: Confidence Intervals Are Equivalent to a 90% Test of Statistical Significance When Two Are Compared") +
  scale_fill_futurama()



```


```{r Causes for overall stress}
#Study and stress levels
m21 %>% 
  group_by(study) %>% filter(q16_3!="NA") %>% 
  mean_ci(q20_2, ci=.76) %>% 
  ggplot(., aes(x=study , y=mean, fill= study)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  theme_hc() +
  theme(text=element_text(family="O", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="O", nudge_y = -10) +
  labs(y="Number of Hours Doing Homework", x=NULL, 
       title="Students Who Study Two Hours Per Day Are Least Stressed;\nStress Plateaus Around Five Hours Per Day",
       caption="Source: March 2021 Survey.\nNote: Confidence Intervals Are Equivalent to a 90% Test of Statistical Significance When Two Are Compared") +
  scale_fill_futurama()

m21_inv %>% 
  group_by(t_inv) %>% filter(p_inv==1) %>% 
  mean_ci(q20_2, ci=.76) %>% 
  ggplot(., aes(x=reorder(t_inv,mean) , y=mean, fill= t_inv)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  coord_flip() +
  theme_hc() +
  theme(text=element_text(family="O", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="O", nudge_y = -10) +
  labs(y="Students' Stress Level", x=NULL, 
       title="Students Involved in Social Justice and Advocacy Are Most Stressed",
       caption="Source: March 2021 Survey.\nNote: Confidence Intervals Are Equivalent to a 90% Test of Statistical Significance When Two Are Compared") +
  gbh_fill()


m21 %>% 
  group_by(polintf) %>% filter(polint!="NA") %>% 
  mean_ci(q20_2, ci=.76) %>% 
  ggplot(., aes(x=polintf, y=mean, fill= polintf)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  theme_hc() +
  theme(text=element_text(family="O", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="O", nudge_y = -10) +
  labs(y="Students Stress Level", x=NULL, 
       title="Students More Interested in Politics Are More Stressed",
       caption="Source: March 2021 Survey.\nNote: Confidence Intervals Are Equivalent to a 90% Test of Statistical Significance When Two Are Compared") +
  scale_fill_futurama()


```



```{r}
#Overall stress this semester
m21 %>% mean_ci(q20_1, ci=0.84)
#Overall stress last semester
m21 %>% mean_ci(q20_2, ci=0.84)

#Academics
m21 %>% 
  group_by(yearf) %>% 
  mean_ci(q21_1)
#Personal finances
m21 %>% mean_ci(q21_2)
#Family
m21 %>% mean_ci(q21_3)
#Mental Health
m21 %>% mean_ci(q21_4)
#Relationships with Friends
m21 %>% mean_ci(q21_5)
#Roommates
m21 %>% mean_ci(q21_6)
#Covid
m21 %>% mean_ci(q21_7)
#What am I eating next
m21 %>% mean_ci(q21_8)
#How much am I eating next
m21 %>% mean_ci(q21_9)

```

```{r}
#Academic Stress
m21_major %>% 
  group_by(t_major) %>% filter(p_major==1) %>% 
  mean_ci(q21_1, ci=.76) %>% 
  ggplot(., aes(x=reorder(t_major,mean) , y=mean, fill= t_major)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  theme_hc() +
  theme(text=element_text(family="O", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="O", nudge_y = -1) +
  scale_y_continuous(limits = c(0,10), 
                     labels = c("Not At All\nStressful", "2.5", "5", "7.5", "Very\nStressful")) +
  labs(x=NULL, y=NULL, 
       title="Arts and Undecided Students Have the Least Academic Stress",
       caption="Source: March 2021 Survey.\nNote: Confidence Intervals Are Equivalent to a 90% Test of Statistical Significance When Two Are Compared") +
  scale_fill_futurama()


m21_inv %>% 
  group_by(t_inv) %>% filter(p_inv==1) %>% 
  mean_ci(q21_1, ci=.76) %>% 
  ggplot(., aes(x=reorder(t_inv,mean) , y=mean, fill= t_inv)) + 
  coord_flip()+
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  theme_hc() +
  theme(text=element_text(family="O", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="O", nudge_y = -1) +
  scale_y_continuous(limits = c(0,10), 
                     labels = c("Not At All\nStressful", "2.5", "5", "7.5", "Very\nStressful")) +
  labs(x=NULL, y=NULL, 
       title="Arts and Undecided Students Have the Least Academic Stress",
       caption="Source: March 2021 Survey.\nNote: Confidence Intervals Are Equivalent to a 90% Test of Statistical Significance When Two Are Compared") +
  scale_fill_futurama()

m21 %>% 
  group_by(invtotf) %>% filter(invtotf!="NA") %>% 
  mean_ci(q21_1, ci=.76) %>% 
  ggplot(., aes(x=invtotf , y=mean, fill= invtotf)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  theme_hc() +
  theme(text=element_text(family="O", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="O", nudge_y = -1) +
  scale_y_continuous(limits = c(0,10), 
                     labels = c("Not At All\nStressful", "2.5", "5", "7.5", "Very\nStressful")) +
  labs(x="Number of Different Organization Types Involved In", y=NULL, 
       title="Involvement Level Does Not Affect Academic Stress",
       caption="Source: March 2021 Survey.\nNote: Confidence Intervals Are Equivalent to a 90% Test of Statistical Significance When Two Are Compared") +
  scale_fill_futurama()






```









