---
title: "How Stressed Are Denison Students?"
subtitle: "March 2021 Survey"
author: "Jacob Dennen"
institute: ""
date: ""
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, "assets/Futuramakage.css", "assets/Futuramakage fonts.css", "assets/ninjutsu.css" , "assets/ninpo.css"]
    self_contained: false
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false



---

class: split-50 with-thick-border

.column.bg-main1[.content.vmiddle[
.center[
##Recently, Siobhan Mitchell wrote another article about stress in which she found two things that caught me attention
]
]]


.column.bg-main5[.split-50.border-white[
.row.slide-in-right[.sliderbox.bg-main5.center.vmiddle[
<br>

]]
.row.slide-in-right[.sliderbox.bg-main5.center.vmiddle[

]]
]]

---

class: split-50 with-thick-border

.column.bg-main1[.content.vmiddle[
.center[
##Recently, Siobhan Mitchell wrote another article about stress in which she found two things that caught me attention
]
]]


.column.bg-main5[.split-50.border-white[
.row.slide-in-right[.sliderbox.bg-main5.center.vmiddle[
<br>
##1. Students are very stressed
]]
.row.slide-in-right[.sliderbox.bg-main5.center.vmiddle[

]]
]]


---

class: split-50 with-thick-border

.column.bg-main1[.content.vmiddle[
.center[
##Recently, Siobhan Mitchell wrote another article about stress in which she found two things that caught me attention
]
]]


.column.bg-main5[.split-50.border-white[
.row[.sliderbox.bg-main5.center.vmiddle[
<br>
##1. Students are very stressed
]]
.row.slide-in-right[.sliderbox.bg-main5.center.vmiddle[
##2.Academics are the main cause of stress
]]
]]




